name: Deploy Apps Script

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Setup clasp credentials
        run: |
          echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}

      - name: Select clasp environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            cp clasp.prod.json .clasp.json
          else
            cp clasp.dev.json .clasp.json
          fi

      - name: Deploy to Apps Script
        run: clasp push
