name: Deploy Google Apps Script

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - ".github/workflows/**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g @google/clasp

      - name: Setup clasp credentials
        run: |
          echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}

      - name: Select clasp environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            cp clasp.prod.json .clasp.json
          else
            cp clasp.dev.json .clasp.json
          fi

      - name: Deploy to Google Apps Script
        run: clasp push -f
